Repository auth0/ruby-auth0, pull requests merged in 2020-06, with the labels that each got.

#222 Improve OIDC compliance: add signature validation support [SDK-987]
  Gemfile.lock
  auth0.gemspec
  lib/auth0.rb
  lib/auth0/algorithm.rb
  lib/auth0/api/authentication_endpoints.rb
  lib/auth0/exception.rb
  lib/auth0/mixins/validation.rb
  spec/lib/auth0/api/authentication_endpoints_spec.rb
  spec/lib/auth0/mixins/validation_spec.rb
  spec/spec_helper.rb
Labels: large

#223 Improve OIDC compliance: add claims validation support [SDK-987]
  lib/auth0/api/authentication_endpoints.rb
  lib/auth0/mixins/validation.rb
  spec/lib/auth0/api/authentication_endpoints_spec.rb
  spec/lib/auth0/mixins/validation_spec.rb
Labels: large

#225 Improve OIDC compliance [SDK-987]
  Gemfile.lock
  README.md
  auth0.gemspec
  lib/auth0.rb
  lib/auth0/algorithm.rb
  lib/auth0/api/authentication_endpoints.rb
  lib/auth0/exception.rb
  lib/auth0/mixins/validation.rb
  spec/lib/auth0/api/authentication_endpoints_spec.rb
  spec/lib/auth0/mixins/validation_spec.rb
  spec/spec_helper.rb
Labels: CH: Added

#226 Release 4.12.0
  CHANGELOG.md
  Gemfile.lock
  lib/auth0/version.rb
Labels: small

#205 Add prompts endpoints
  lib/auth0/api/v2.rb
  lib/auth0/api/v2/prompts.rb
  spec/lib/auth0/api/v2/prompts_spec.rb
Labels: small

#227 Release 4.13.0
  CHANGELOG.md
  Gemfile.lock
  lib/auth0/version.rb
Labels: small

#229 Remove iat claim value check
  lib/auth0/mixins/validation.rb
  spec/lib/auth0/mixins/validation_spec.rb
Labels: CH: Removed, small
