Repository auth0/ruby-auth0, pull requests merged in 2020-05, with the labels that each got.

#217 [SDK-1542] Add client secret to Passwordless flow since it is now required
  lib/auth0/api/authentication_endpoints.rb
  spec/lib/auth0/api/authentication_endpoints_spec.rb
Labels: CH: Added, small

#218 [SDK-1542] Updated info about testing in the readme
  .env.example
  DEPLOYMENT.md
  README.md
  spec/spec_helper.rb
Labels: documentation, tiny

#219 Release 4.11.0 [SDK-1626]
  CHANGELOG.md
  Gemfile.lock
  lib/auth0/version.rb
Labels: small
