Repository auth0/ruby-auth0, pull requests merged in 2020-10, with the labels that each got.

#237 New Email Verification Fields
  lib/auth0/api/v2/jobs.rb
  lib/auth0/api/v2/tickets.rb
  spec/integration/lib/auth0/api/v2/api_jobs_spec.rb
  spec/integration/lib/auth0/api/v2/api_tickets_spec.rb
  spec/lib/auth0/api/v2/jobs_spec.rb
  spec/lib/auth0/api/v2/tickets_spec.rb
Labels: CH: Added

#240 Addressable URI Escape
  lib/auth0/mixins/httpproxy.rb
  spec/lib/auth0/mixins/httpproxy_spec.rb
Labels: CH: Deprecated

#241 Add pagination to user permissions
  lib/auth0/api/v2/users.rb
  spec/lib/auth0/api/v2/users_spec.rb
Labels: CH: Added, tiny

#243 Remove old documentation tools
  .gitignore
  .yardoc/checksums
  .yardoc/complete
  .yardoc/object_types
  .yardoc/objects/root.dat
  .yardoc/proxy_types
  Gemfile
  Gemfile.lock
  README.md
  Rakefile
  auth0.gemspec
  deploy_documentation.sh
  doc_config/templates/default/fulldoc/html/css/full_list.css
  doc_config/templates/default/fulldoc/html/css/style.css
  doc_config/templates/default/layout/html/breadcrumb.erb
  doc_config/templates/default/layout/html/footer.erb
  doc_config/templates/default/layout/html/headers.erb
  doc_config/templates/default/layout/html/layout.erb
  examples/ruby-api/.gitignore
Labels: small

#183 Don't define structs as top-level constants
  lib/auth0/api/authentication_endpoints.rb
  lib/auth0/mixins/access_token_struct.rb
  lib/auth0/mixins/api_token_struct.rb
  lib/auth0/mixins/permission_struct.rb
  lib/auth0/mixins/validation.rb
  spec/integration/lib/auth0/api/v2/api_roles_spec.rb
  spec/integration/lib/auth0/api/v2/api_users_spec.rb
  spec/lib/auth0/api/v2/roles_spec.rb
  spec/lib/auth0/api/v2/users_spec.rb
Labels: CH: Breaking Change

#244 Fix create_user implementation
  lib/auth0/api/v2/users.rb
  spec/lib/auth0/api/v2/users_spec.rb
Labels: CH: Breaking Change, tiny

#247 Addressable dependency
  CHANGELOG.md
  Gemfile.lock
  auth0.gemspec
Labels: CH: Fixed
