Repository auth0/ruby-auth0, pull requests merged in 2020-04, with the labels that each got.

#210 Update dependencies and CI script
  .circleci/config.yml
  Gemfile.lock
Labels: CH: Security, tiny

#209 Pass client_id, audience at Auth0::Api::V2::ClientGrants#client_grants
  lib/auth0/api/v2/client_grants.rb
  spec/lib/auth0/api/v2/client_grants_spec.rb
Labels: CH: Added, tiny

#214 Added support for name_filter parameter [SDK-1607]
  lib/auth0/api/v2/roles.rb
  spec/lib/auth0/api/v2/roles_spec.rb
Labels: CH: Added, tiny

#215 Release 4.10.0
  CHANGELOG.md
  Gemfile.lock
  lib/auth0/version.rb
Labels: small

#216 Add development notes
  DEPLOYMENT.md
  README.md
Labels: small
