Repository auth0/ruby-auth0, pull requests merged in 2021-09, with the labels that each got.

#293 [SDK-2718] New Actions endpoints
  lib/auth0/api/v2.rb
  lib/auth0/api/v2/actions.rb
  lib/auth0/exception.rb
  spec/lib/auth0/api/v2/actions_spec.rb
Labels: CH: Added, review:medium

#295 Add New Grants endpoints
  lib/auth0/api/v2.rb
  lib/auth0/api/v2/grants.rb
  spec/lib/auth0/api/v2/grants_spec.rb
Labels: CH: Added

#297 Deprecate change_password in favor of reset_password
  lib/auth0/api/authentication_endpoints.rb
Labels: CH: Deprecated
