Repository auth0/ruby-auth0, pull requests merged in 2021-07, with the labels that each got.

#280 Ensure email param is properly encoded in `delete_connection_user` [SDK-2660]
  README.md
  lib/auth0/api/v2/connections.rb
  spec/fixtures/vcr_cassettes/Auth0_Api_V2_Connections/_connection/_filters/should_exclude_the_fields_indicated.yml
  spec/fixtures/vcr_cassettes/Auth0_Api_V2_Connections/_connection/_filters/should_include_the_fields_indicated.yml
  spec/fixtures/vcr_cassettes/Auth0_Api_V2_Connections/_connection/should_find_the_correct_connection.yml
  spec/fixtures/vcr_cassettes/Auth0_Api_V2_Connections/_connections/_filters/should_include_previously-created_connection_when_filtered.yml
  spec/fixtures/vcr_cassettes/Auth0_Api_V2_Connections/_connections/_filters/should_should_exclude_the_fields_indicated_from_filtered_results.yml
  spec/fixtures/vcr_cassettes/Auth0_Api_V2_Connections/_connections/_filters/should_should_include_the_fields_indicated_from_filtered_results.yml
  spec/fixtures/vcr_cassettes/Auth0_Api_V2_Connections/_connections/should_include_the_previously_created_connection.yml
  spec/fixtures/vcr_cassettes/Auth0_Api_V2_Connections/_connections/should_not_be_empty.yml
  spec/fixtures/vcr_cassettes/Auth0_Api_V2_Connections/_delete_connection/should_delete_the_connection.yml
  spec/fixtures/vcr_cassettes/Auth0_Api_V2_Connections/_delete_connection_user/should_delete_the_user_created.yml
  spec/fixtures/vcr_cassettes/Auth0_Api_V2_Connections/_update_connection/should_update_the_connection.yml
  spec/fixtures/vcr_cassettes/Auth0_Api_V2_Connections/create_test_connection.yml
  spec/lib/auth0/api/v2/connections_spec.rb
Labels: CH: Fixed, review:tiny

#279 Do not lock dependencies to minor version
  auth0.gemspec
Labels: CH: Changed

#275 Adds Rotating Refresh Token type to Device Credentials
  lib/auth0/api/v2/device_credentials.rb
  spec/lib/auth0/api/v2/device_credentials_spec.rb
Labels: CH: Added

#287 Change strategy when normalizing path
  lib/auth0/mixins/httpproxy.rb
  spec/lib/auth0/mixins/httpproxy_spec.rb
  spec/support/dummy_class_for_proxy.rb
Labels: CH: Changed, review:small
