Repository auth0/ruby-auth0, pull requests merged in 2021-04, with the labels that each got.

#265 [SDK-2456] Remove Organizations Beta Labelling
  README.md
Labels: review:tiny

#264 Organizations feature
  .circleci/config.yml
  lib/auth0/api/v2.rb
  lib/auth0/api/v2/jobs.rb
  lib/auth0/api/v2/organizations.rb
  lib/auth0/api/v2/tickets.rb
  lib/auth0/api/v2/users.rb
  lib/auth0/exception.rb
  spec/lib/auth0/api/v2/jobs_spec.rb
  spec/lib/auth0/api/v2/organizations_spec.rb
  spec/lib/auth0/api/v2/tickets_spec.rb
  spec/lib/auth0/api/v2/users_spec.rb
Labels: CH: Added

#261 Add api_identifier as an accepted configurable
  README.md
  lib/auth0/api/authentication_endpoints.rb
  lib/auth0/mixins/initializer.rb
  spec/lib/auth0/client_spec.rb
Labels: CH: Added

#266 Adds Branding [SDK-2485]
  lib/auth0/api/v2.rb
  lib/auth0/api/v2/branding.rb
  spec/lib/auth0/api/v2/branding_spec.rb
Labels: CH: Added

#267 Org idtoken validation guidance [SDK-2457]
  README.md
Labels: CH: Added

#269 Fixes create_organizations_enabled_connection
  lib/auth0/api/v2/organizations.rb
  spec/lib/auth0/api/v2/organizations_spec.rb
Labels: CH: Fixed

#272 Properly handle headers when parsing x_ratelimit_reset in exception
  lib/auth0/exception.rb
  spec/lib/auth0/mixins/httpproxy_spec.rb
Labels: CH: Fixed
